In [4]:
import numpy as np
import pandas as pd

from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.ensemble import RandomForestClassifier 
from matplotlib.pyplot import figure

# Read CSV file and import the data as DataFrame
filename = "C:\\Work\\Workspace\\Project\\record_second.csv"
names = ['name', 'address', 'phoneNumber', 'region','age', 'callCount', 'activeCallTime', 
         'smsCount', 'dataUsage', 'Subscription_1', 'Subscription_2', 
         'Subscription_3', 'Subscription_4', 'plan']
dataset = pd.read_csv(filename, names=names)

# The below values are scrapped since they do not contribute to the prediction
dataset.pop('name')
dataset.pop('address')
dataset.pop('phoneNumber')

#print(dataset.describe())
print(dataset.groupby('plan').size())
       
# To convert the string to number. Here city names are converted to integer.
le = LabelEncoder()
for col in dataset.columns:
    
    if col == 'region':
        dataset[col] = LabelEncoder().fit_transform(dataset[col])

array = dataset.values
x = array[:,0:9]
y = array[:,10]

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  


'''
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")  
classifier.fit(x_train, y_train)

y_pred= classifier.predict(x_test) 
print(y_pred)

#model = RandomForestClassifier(n_estimators= 10, criterion="entropy")
#model.fit(x_train, x_train)
#predictions = model.predict(x_test)
# Evaluate predictions
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
'''

 
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")  
classifier.fit(x_train, y_train)


testdatafile = "C:\\Work\\Workspace\\Project\\record_second.csv"
names = ['name', 'address', 'phoneNumber', 'region','age', 'callCount', 'activeCallTime', 
         'smsCount', 'dataUsage', 'Subscription_1', 'Subscription_2', 
         'Subscription_3', 'Subscription_4', 'plan']
testdataset = pd.read_csv(testdatafile, names=names)

# The below values are scrapped since they do not contribute to the prediction
testdataset.pop('name')
testdataset.pop('address')
testdataset.pop('phoneNumber')

# To convert the string to number. Here city names are converted to integer.
le = LabelEncoder()
for col in testdataset.columns:
    
    if col == 'region':
        testdataset[col] = LabelEncoder().fit_transform(testdataset[col])

testdataarray = testdataset.values
x = testdataarray[:,0:9]
y = testdataarray[:,10]

print(x)

y_pred= classifier.predict(x)

print(y_pred)

'''
low_limit = 0
upper_limit = 1
for i in range(20):
    y_pred= classifier.predict(x_test[low_limit:upper_limit])
    #print(y_pred)
    if(y_pred != y_test[low_limit:upper_limit]):
        print("upper_limit: ", upper_limit, y_pred)
       
    low_limit = low_limit + 1
    upper_limit = upper_limit + 1
'''

plan
1    1985
2    2978
3    4368
4    5559
5    2978
6    1389
7     595
dtype: int64
[[ 2 18  5 ...  0  0  0]
 [ 5 42  4 ...  0  0  0]
 [ 2 30  4 ...  0  0  0]
 ...
 [ 0 42 20 ...  0  1  1]
 [ 7 43 38 ...  0  1  0]
 [ 1 40 31 ...  1  0  0]]
[1 1 1 ... 6 7 7]


'\nlow_limit = 0\nupper_limit = 1\nfor i in range(20):\n    y_pred= classifier.predict(x_test[low_limit:upper_limit])\n    #print(y_pred)\n    if(y_pred != y_test[low_limit:upper_limit]):\n        print("upper_limit: ", upper_limit, y_pred)\n       \n    low_limit = low_limit + 1\n    upper_limit = upper_limit + 1\n'