In [46]:
import numpy as np
import pandas as pd

from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import KBinsDiscretizer
from matplotlib.pyplot import figure

# Read CSV file and import the data as DataFrame
filename = "E:\\Work\\github\\mtech\\FinalSemProject\\data\\record_second.csv"
names = ['name', 'address', 'phoneNumber', 'region','age', 'callCount', 'activeCallTime', 
         'smsCount', 'dataUsage', 'Subscription_1', 'Subscription_2', 
         'Subscription_3', 'Subscription_4', 'plan']
dataset = pd.read_csv(filename, names=names)

# The below values are scrapped since they do not contribute to the prediction
dataset.pop('name')
dataset.pop('address')
dataset.pop('phoneNumber')

#print(dataset.describe())
print(dataset.groupby('plan').size())

def descritize(column_name, num_of_bins):
    data = dataset[column_name].values
    df = pd.DataFrame(data,columns=[column_name])
    trans = KBinsDiscretizer(n_bins=num_of_bins, encode='ordinal', strategy='uniform')
    data = trans.fit_transform(df)
    return pd.DataFrame(data)
        
        
# To convert the string to number. Here city names are converted to integer.
le = LabelEncoder()
for col in dataset.columns:
    
    if col == 'region':
        dataset[col] = LabelEncoder().fit_transform(dataset[col])

array = dataset.values
x = array[:,0:9]
y = array[:,10]

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.20, random_state=0)

from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")  
classifier.fit(x_train, y_train)

y_pred= classifier.predict(x_test)  
print(y_pred)

#model = RandomForestClassifier(n_estimators= 10, criterion="entropy")
#model.fit(x_train, x_train)
#predictions = model.predict(x_test)
# Evaluate predictions
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

plan
1    1985
2    2978
3    4368
4    5559
5    2978
6    1389
7     595
dtype: int64
[2 3 2 ... 2 2 6]
0.936036262906069
[[383   4   0   0   0   0   0]
 [ 31 538   0   0   0   0   0]
 [  0   2 890  16   0   0   0]
 [  0   0 124 977   0   0   0]
 [  0   0   0  62 548   0   0]
 [  0   0   0   1   4 276   0]
 [  0   0   0   0   0  10 105]]
              precision    recall  f1-score   support

           1       0.93      0.99      0.96       387
           2       0.99      0.95      0.97       569
           3       0.88      0.98      0.93       908
           4       0.93      0.89      0.91      1101
           5       0.99      0.90      0.94       610
           6       0.97      0.98      0.97       281
           7       1.00      0.91      0.95       115

    accuracy                           0.94      3971
   macro avg       0.95      0.94      0.95      3971
weighted avg       0.94      0.94      0.94      3971



In [ ]:
'''
One reason to discretize continuous features is to improve 
signal-to-noise ratio. Fitting a model to bins reduces the 
impact that small fluctuates in the data has on the model, 
often small fluctuates are just noise. Each bin "smooths" 
out the fluctuates/noises in sections of the data.
'''

from pandas import read_csv
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.preprocessing import LabelEncoder

import numpy as np

url = "E:\\Work\\github\\mtech\\FinalSemProject\\data\\record_second.csv"
names = ['name', 'address', 'phoneNumber', 'region','age', 'callCount', 'activeCallTime', 
         'smsCount', 'dataUsage', 'Subscription_1', 'Subscription_2', 
         'Subscription_3', 'Subscription_4', 'plan']
dataset = read_csv(url, names=names)

#print(dataset.info())
#print(dataset.describe())

'''
The below command can be used to find the unique elements in the data set,
which can be eliminated for further processing
'''

dataset.pop('name')
dataset.pop('address')
dataset.pop('phoneNumber')
#dataset.pop('region')

#print(dataset.describe(include=np.object))

#print(dataset.groupby('plan').size())

#dataset.plot(kind='box', subplots=True, layout=(5,2), sharex=False, sharey=False)
#pyplot.show()


#dataset.hist()
'''
fig, axes = pyplot.subplots(figsize=(19,10), dpi=50, nrows=3, ncols=4)
flat_axes = list(axes.reshape(-1))
fig.delaxes(flat_axes.pop(-1))
fig.delaxes(flat_axes.pop(-1))

dataset.hist(ax=flat_axes, alpha=0.5, label='x',color='b')

pyplot.plot()
'''
le = LabelEncoder()


df = dataset[dataset.columns[:]].apply(le.fit_transform)

array = df.values
X = array[:,0:9]
y = array[:,10]

X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.20, random_state=1, shuffle=True)
# Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
models.append(('RF', RandomForestClassifier(n_estimators= 10, criterion="entropy")))
# evaluate each model in turn
results = []
names = []
print("Start Model Analysis...")
for name, model in models:
	kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
	cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
	results.append(cv_results)
	names.append(name)
	print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))

print("Completed Model Analysis...")
# Compare Algorithms
pyplot.boxplot(results, labels=names)
pyplot.title('Algorithm Comparison')
pyplot.show()

model = RandomForestClassifier(n_estimators= 10, criterion="entropy")
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
# Evaluate predictions
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

Start Model Analysis...


C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  StratifiedKFold(n_splits=2, random_state=None, shuffle=False)


LR: 0.551436 (0.010582)


C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  
C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  StratifiedKFold(n_splits=2, random_state=None, shuffle=False)


LDA: 0.546089 (0.007541)
KNN: 0.598727 (0.010498)


C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  StratifiedKFold(n_splits=2, random_state=None, shuffle=False)


CART: 0.779693 (0.008480)
NB: 0.546524 (0.013320)


C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
C:\Users\Ramji\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  StratifiedKFold(n_splits=2, random_state=None, shuffle=False)


In [5]:
import numpy as np
import pandas as pd

from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import KBinsDiscretizer
from matplotlib.pyplot import figure

# Read CSV file and import the data as DataFrame
filename = "E:\\Work\\github\\mtech\\FinalSemProject\\data\\record_second.csv"
names = ['name', 'address', 'phoneNumber', 'region','age', 'callCount', 'activeCallTime', 
         'smsCount', 'dataUsage', 'Subscription_1', 'Subscription_2', 
         'Subscription_3', 'Subscription_4', 'plan']
dataset = pd.read_csv(filename, names=names)

# The below values are scrapped since they do not contribute to the prediction
dataset.pop('name')
dataset.pop('address')
dataset.pop('phoneNumber')

#print(dataset.describe())
print(dataset.groupby('plan').size())

def descritize(column_name, num_of_bins):
    data = dataset[column_name].values
    df = pd.DataFrame(data,columns=[column_name])
    trans = KBinsDiscretizer(n_bins=num_of_bins, encode='ordinal', strategy='uniform')
    data = trans.fit_transform(df)
    return pd.DataFrame(data)
        
        
# To convert the string to number. Here city names are converted to integer.
le = LabelEncoder()
for col in dataset.columns:
    
    if col == 'region':
        dataset[col] = LabelEncoder().fit_transform(dataset[col])

array = dataset.values
x = array[:,0:9]
y = array[:,10]

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

print(x_test[0:20])
print(y_test[0:20])

'''
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")  
classifier.fit(x_train, y_train)

y_pred= classifier.predict(x_test) 
print(y_pred)

#model = RandomForestClassifier(n_estimators= 10, criterion="entropy")
#model.fit(x_train, x_train)
#predictions = model.predict(x_test)
# Evaluate predictions
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
'''

from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")  
classifier.fit(x_train, y_train)

low_limit = 0
upper_limit = 1
for i in range(20):
    y_pred= classifier.predict(x_test[low_limit:upper_limit])
    #print(y_pred)
    if(y_pred != y_test[low_limit:upper_limit]):
        print("upper_limit: ", upper_limit, y_pred)
       
    low_limit = low_limit + 1
    upper_limit = upper_limit + 1


plan
1       1985
2       2978
3       4368
4       5559
5       2978
6       1389
7        595
plan       1
dtype: int64
[[8 '20' '2' '9' '10' '24' '0' '0' '0']
 [8 '30' '18' '18' '8' '721' '0' '0' '0']
 [1 '20' '7' '10' '1' '4' '0' '0' '0']
 [2 '31' '5' '20' '17' '448' '0' '0' '0']
 [1 '18' '4' '4' '0' '15' '0' '0' '0']
 [8 '33' '16' '22' '10' '259' '0' '0' '0']
 [9 '68' '3' '10' '2' '28' '0' '0' '0']
 [0 '33' '27' '27' '46' '2736' '0' '0' '1']
 [4 '37' '16' '22' '20' '1465' '0' '1' '0']
 [9 '65' '13' '23' '9' '651' '0' '0' '0']
 [3 '69' '4' '6' '6' '25' '0' '0' '0']
 [4 '49' '11' '11' '10' '408' '0' '0' '0']
 [3 '76' '5' '13' '20' '168' '0' '0' '0']
 [3 '81' '4' '14' '4' '13' '0' '0' '0']
 [2 '33' '6' '21' '18' '313' '0' '0' '0']
 [6 '38' '17' '25' '7' '604' '0' '0' '0']
 [0 '31' '13' '13' '9' '183' '0' '0' '0']
 [2 '59' '5' '16' '5' '25' '0' '0' '0']
 [4 '52' '4' '13' '1' '25' '0' '0' '0']
 [0 '73' '8' '19' '18' '886' '0' '0' '0']]
['2' '4' '2' '3' '2' '4' '2' '6' '6' '4' '2' '3' '

ValueError: could not convert string to float: 'subscription_c'